version: '{build}'

os: Visual Studio 2015

environment:
  matrix:
    - compiler: msvc-15-seh
      generator: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      enabled_on_pr: yes

configuration:
  - Debug
  - Release

build:
  project: JSImpl/solution/JSImpl.sln
  verbosity: minimal

test_script:
  - '%APPVEYOR_BUILD_FOLDER%/JSImpl/build/bin/%CONFIGURATION%/Test.exe'

clone_depth: 1

skip_commits:
  files:
    - '**/*.md'

branches:
    except:
        - gh-pages
