baseURL = "https://sofiacpp.github.io/IPL/"
languageCode = "en-us"
title = "Implementation of Programming Languages"
theme = "natrium"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"

[taxonomies]
    category = "categories"  
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = -120

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = -130

[params]
    description = "Course on implementing a programming language"
    GitHubURL = "https://github.com/SofiaCPP/IPL"

    [params.logo]
    url = "wrench.png"
    width = 50
    height = 50
    alt = "Logo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
    highlight_theme = "monokai"
    slide_number = true
    transition = "none"

