baseURL = "https://sofiacpp.github.io/IPL/"
languageCode = "en-us"
title = "Implementation of Programming Languages"
theme = [ "hugo-clarity", "reveal-hugo" ]

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"

[taxonomies]
    edition = "edition"  
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = -120

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = -130

[params]
    name = "IPL"
    description = "Course on implementing programming languages"
    GitHubURL = "https://github.com/SofiaCPP/IPL"
    numberOfTagsShown = 14

    [params.logo]
    url = "images/wrench.png"
    width = 48
    height = 48
    alt = "Logo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
    highlight_theme = "monokai"
    slide_number = true
    transition = "none"

